# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *
from .random import *
from .random_component import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_apolloconfig.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_apolloconfig.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "apolloconfig",
  "mod": "index",
  "fqn": "pulumi_apolloconfig",
  "classes": {
   "apolloconfig:index:Random": "Random",
   "apolloconfig:index:RandomComponent": "RandomComponent"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "apolloconfig",
  "token": "pulumi:providers:apolloconfig",
  "fqn": "pulumi_apolloconfig",
  "class": "Provider"
 }
]
"""
)
